var annotated_dup =
[
    [ "BackButton", "class_back_button.html", "class_back_button" ],
    [ "BaseAnimalScript", "class_base_animal_script.html", null ],
    [ "BaseResourceScript", "class_base_resource_script.html", null ],
    [ "Billboard", "class_billboard.html", null ],
    [ "CanvasVars", "class_canvas_vars.html", "class_canvas_vars" ],
    [ "Classes", "class_classes.html", "class_classes" ],
    [ "ClickYieldIcon", "class_click_yield_icon.html", "class_click_yield_icon" ],
    [ "CloseUI", "class_close_u_i.html", "class_close_u_i" ],
    [ "CreateHex", "class_create_hex.html", "class_create_hex" ],
    [ "CurrentLeader", "class_current_leader.html", "class_current_leader" ],
    [ "CurrentMap", "class_current_map.html", "class_current_map" ],
    [ "DrawCities", "class_draw_cities.html", "class_draw_cities" ],
    [ "DrawTrapezium", "class_draw_trapezium.html", "class_draw_trapezium" ],
    [ "ExitToDesktop", "class_exit_to_desktop.html", "class_exit_to_desktop" ],
    [ "HealthBarScript", "class_health_bar_script.html", "class_health_bar_script" ],
    [ "Hex", "struct_hex.html", "struct_hex" ],
    [ "MapScript", "class_map_script.html", "class_map_script" ],
    [ "MusicVolume", "class_music_volume.html", "class_music_volume" ],
    [ "NewMenu", "class_new_menu.html", "class_new_menu" ],
    [ "OpenOverview", "class_open_overview.html", "class_open_overview" ],
    [ "OutLineScript", "class_out_line_script.html", "class_out_line_script" ],
    [ "PlayerMovement", "class_player_movement.html", "class_player_movement" ],
    [ "PreventDrag", "class_prevent_drag.html", "class_prevent_drag" ],
    [ "Properties", "class_properties.html", "class_properties" ],
    [ "QuitToMenu", "class_quit_to_menu.html", "class_quit_to_menu" ],
    [ "ReturnToGame", "class_return_to_game.html", "class_return_to_game" ],
    [ "SetCurrentLeader", "class_set_current_leader.html", "class_set_current_leader" ],
    [ "SetCurrentMap", "class_set_current_map.html", "class_set_current_map" ],
    [ "StartButton", "class_start_button.html", "class_start_button" ],
    [ "TileScript", "class_tile_script.html", "class_tile_script" ]
];